# Generated by Django 4.1.13 on 2025-05-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_alter_assignmentresponse_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionembedding',
            new_name='question_em_questio_c2ff17_idx',
            old_name='interface_q_questio_51b7c5_idx',
        ),
        migrations.AlterModelTable(
            name='questionembedding',
            table='question_embeddings',
        ),
    ]
