# Generated by Django 4.1.13 on 2025-05-19 14:09

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_rename_interface_q_questio_51b7c5_idx_question_em_questio_c2ff17_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
